# docker-compose.yml

version: '3.2'
networks:
  frontend:
  backend:
services:
  delivery-mysql:
    image: mysql
    container_name: delivery-mysql
    volumes:
      - "delivery-mysql-data:/var/lib/mysql/data"   
    environment:
      MYSQL_DATABASE: db_delivery
      MYSQL_USER: devRoot
      MYSQL_PASSWORD: Lucie-2009      
      MYSQL_ROOT_PASSWORD: Lucie-2009
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 
    ports:
    - "3600:3600"
    networks:
      - backend
      
  delivery-back:
    image: delivery-back
    container_name: delivery-back
    depends_on:
      - delivery-mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://delivery-mysql:3306/db_delivery?allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    ports:
      - "8080:8080"
    expose:
      - "8080"
    links:
      - delivery-mysql:database
    networks:
      - backend
      - frontend
  
  delivery-front:
    image: jjaurensan/delivery-front
    container_name: delivery-front
    links:
      - delivery-back
    ports:
      - "4200:80"
    depends_on:
      - delivery-back
    networks:
      - frontend
volumes:
  delivery-mysql-data: